package com.lqc.common.protocol;

public enum MessageType {
    // Authentication
    LOGIN_REQUEST, LOGIN_RESPONSE,
    REGISTER_REQUEST, REGISTER_RESPONSE,

    // Rooms
    CREATE_ROOM_REQUEST, CREATE_ROOM_RESPONSE,
    JOIN_ROOM_REQUEST, JOIN_ROOM_RESPONSE,
    LEAVE_ROOM_REQUEST, LEAVE_ROOM_RESPONSE,
    INVITE_TO_ROOM_REQUEST, INVITE_TO_ROOM_RESPONSE,
    REMOVE_MEMBER_REQUEST, REMOVE_MEMBER_RESPONSE,
    LIST_ROOMS_REQUEST, LIST_ROOMS_RESPONSE,
    LIST_PUBLIC_ROOMS_REQUEST, LIST_PUBLIC_ROOMS_RESPONSE,
    ROOM_MEMBERS_REQUEST, ROOM_MEMBERS_RESPONSE,
    LIST_USERS_REQUEST, LIST_USERS_RESPONSE,
    DM_HISTORY_REQUEST,

    // Messages
    SEND_MESSAGE_REQUEST, SEND_MESSAGE_RESPONSE,
    PRIVATE_MESSAGE_REQUEST, PRIVATE_MESSAGE_RESPONSE,
    GET_HISTORY_REQUEST, GET_HISTORY_RESPONSE,

    // Files
    FILE_UPLOAD_START, FILE_UPLOAD_START_RESPONSE,
    FILE_UPLOAD_CHUNK, FILE_UPLOAD_CHUNK_ACK,
    FILE_UPLOAD_COMPLETE, FILE_UPLOAD_COMPLETE_RESPONSE,
    FILE_DOWNLOAD_REQUEST, FILE_DOWNLOAD_START,
    FILE_DOWNLOAD_CHUNK, FILE_DOWNLOAD_COMPLETE,

    // Reactions
    ADD_REACTION_REQUEST, REMOVE_REACTION_REQUEST, REACTION_RESPONSE,

    // Status
    STATUS_UPDATE_REQUEST, STATUS_UPDATE_RESPONSE,

    // Profile
    UPDATE_PROFILE_REQUEST, UPDATE_PROFILE_RESPONSE,
    AVATAR_REQUEST, AVATAR_RESPONSE,

    // Notifications (server -> client)
    NEW_MESSAGE_NOTIFICATION,
    USER_JOINED_NOTIFICATION,
    USER_LEFT_NOTIFICATION,
    ADDED_TO_ROOM_NOTIFICATION,
    REMOVED_FROM_ROOM_NOTIFICATION,
    STATUS_CHANGE_NOTIFICATION,
    REACTION_NOTIFICATION,
    USER_TYPING_NOTIFICATION,

    // Error
    ERROR_RESPONSE
}
